# GRUVBOX — egel/tmux-gruvbox
source-file ~/tmux_themes/themes/_common.tmux

set -g window-style 'bg=#282828'
set -g window-active-style 'bg=#282828'
set -g pane-border-style 'fg=#504945'
set -g pane-active-border-style 'fg=#fabd2f'
set -g message-style 'bg=#fabd2f,fg=#282828'

# tmux-gruvbox plugin
set -g @tmux-gruvbox 'dark'
set -g @tmux-gruvbox-statusbar-alpha 'false'

# Initialize plugin
run ~/.tmux/plugins/tmux-gruvbox/gruvbox-tpm.tmux

# Prefix indicator
set -ga status-left "#{?client_prefix,#[fg=#fb4934]●,#[fg=#504945]●} "
