# ROSE-PINE — rose-pine/tmux plugin (moon variant)
source-file ~/tmux_themes/themes/_common.tmux

set -g window-style 'bg=#232136'
set -g window-active-style 'bg=#232136'
set -g pane-border-style 'fg=#393552'
set -g pane-active-border-style 'fg=#c4a7e7'
set -g message-style 'bg=#c4a7e7,fg=#232136'

# Rose Pine plugin config
set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'on'
set -g @rose_pine_date_time '%H:%M %d-%b'
set -g @rose_pine_directory 'on'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'

# Initialize plugin
run ~/.tmux/plugins/rose-pine/rose-pine.tmux

# Prefix indicator
set -ga status-left "#{?client_prefix,#[fg=#eb6f92]●,#[fg=#393552]●} "
